"""Single source of truth for every disease / pest the app knows about.

To add a new disease:
  1. Add an entry to DISEASES below (label, crop, pathogen, favourable weather, advice).
  2. Add its id to the right crop in CROP_DISEASES.
  3. Add a scoring rule in classifier.py (_scores).
  4. Add its name + advice in static/i18n.js (NAMES, ADVMAP, ADV) for EN / HI / TE.
Nothing else needs to change.
"""

DISEASES = {
    # ------------------------------------------------------------ existing
    "tomato_early_blight": {
        "label": "Tomato — Early Blight", "crop": "Tomato",
        "pathogen": "Alternaria solani (fungus)",
        "favorable": {"humidity_min": 80, "temp_range": (24, 29), "rain_boost": True},
        "steps": ["Remove and destroy affected lower leaves to slow spread",
                  "Apply a chlorothalonil or mancozeb-based fungicide every 7-10 days",
                  "Avoid overhead irrigation; water at the base instead"],
        "organic": "Neem oil spray (2%) every 5-7 days as a preventive layer",
        "dosage": "Mancozeb 75% WP — 2.5g/litre of water",
    },
    "tomato_late_blight": {
        "label": "Tomato — Late Blight", "crop": "Tomato",
        "pathogen": "Phytophthora infestans (oomycete)",
        "favorable": {"humidity_min": 90, "temp_range": (10, 24), "rain_boost": True},
        "steps": ["Isolate affected plants immediately — this spreads fast",
                  "Apply a copper oxychloride or cymoxanil-based fungicide within 24-48 hours",
                  "Improve field drainage and spacing to reduce humidity around plants"],
        "organic": "Copper-based organic fungicide (Bordeaux mixture)",
        "dosage": "Copper oxychloride 50% WP — 3g/litre of water",
    },
    "potato_late_blight": {
        "label": "Potato — Late Blight", "crop": "Potato",
        "pathogen": "Phytophthora infestans (oomycete)",
        "favorable": {"humidity_min": 90, "temp_range": (10, 24), "rain_boost": True},
        "steps": ["Isolate affected plants immediately — this spreads fast",
                  "Apply a copper oxychloride or cymoxanil-based fungicide within 24-48 hours",
                  "Improve field drainage and spacing to reduce humidity around plants"],
        "organic": "Copper-based organic fungicide (Bordeaux mixture)",
        "dosage": "Copper oxychloride 50% WP — 3g/litre of water",
    },
    "wheat_leaf_rust": {
        "label": "Wheat — Leaf Rust", "crop": "Wheat",
        "pathogen": "Puccinia triticina (fungus)",
        "favorable": {"humidity_min": 70, "temp_range": (15, 22), "rain_boost": False},
        "steps": ["Apply a propiconazole or tebuconazole-based fungicide at first sign",
                  "Monitor neighbouring fields — rust spreads via windborne spores",
                  "Avoid excess nitrogen fertilizer, which increases susceptibility"],
        "organic": "Sulfur dust application in early stages",
        "dosage": "Propiconazole 25% EC — 1ml/litre of water",
    },
    "wheat_powdery_mildew": {
        "label": "Wheat — Powdery Mildew", "crop": "Wheat", "pathogen": "Blumeria graminis (fungus)",
        "favorable": {"humidity_min": 70, "temp_range": (15, 25), "rain_boost": False},
        "steps": ["Spray wettable sulphur or hexaconazole at first white patches",
                  "Improve air flow; avoid dense sowing",
                  "Avoid excess nitrogen fertilizer"],
        "organic": "Diluted buttermilk spray",
        "dosage": "Wettable sulphur 80% WP — 2.5g/litre of water",
    },
    "rice_blast": {
        "label": "Rice — Blast", "crop": "Rice",
        "pathogen": "Magnaporthe oryzae (fungus)",
        "favorable": {"humidity_min": 85, "temp_range": (25, 28), "rain_boost": True},
        "steps": ["Drain standing water temporarily to reduce humidity at the base",
                  "Apply a tricyclazole-based fungicide as soon as lesions appear",
                  "Use balanced nitrogen — split doses rather than one heavy application"],
        "organic": "Pseudomonas fluorescens bio-fungicide spray",
        "dosage": "Tricyclazole 75% WP — 0.6g/litre of water",
    },
    "pest_aphid": {
        "label": "Pest — Aphids / Whitefly", "crop": "Any", "pathogen": None,
        "favorable": {"humidity_min": 50, "temp_range": (25, 32), "rain_boost": False},
        "steps": ["Spray neem oil and install yellow sticky traps",
                  "If infestation is severe, spray imidacloprid as per label",
                  "Check the underside of leaves every 2-3 days"],
        "organic": "Yellow sticky traps",
        "dosage": "Neem oil — 5ml/litre of water",
    },
    "healthy": {
        "label": "Healthy — no disease detected", "crop": "Unknown", "pathogen": None,
        "favorable": None,
        "steps": ["No treatment needed", "Continue routine monitoring, especially after rain"],
        "organic": None, "dosage": None,
    },

    # ----------------------------------------------------------------- NEW
    # Tomato
    "tomato_leaf_curl": {
        "label": "Tomato — Leaf Curl Virus", "crop": "Tomato",
        "pathogen": "Tomato leaf curl virus (spread by whitefly)",
        "favorable": {"humidity_min": 40, "temp_range": (26, 35), "rain_boost": False},
        "steps": ["Uproot and burn badly infected plants — a virus cannot be cured",
                  "Control whitefly, the carrier: spray imidacloprid as per label",
                  "Install yellow sticky traps and remove weeds around the field"],
        "organic": "Neem oil 5ml/litre plus yellow sticky traps",
        "dosage": "Imidacloprid 17.8% SL — 0.3ml/litre of water",
    },
    "tomato_septoria": {
        "label": "Tomato — Septoria Leaf Spot", "crop": "Tomato",
        "pathogen": "Septoria lycopersici (fungus)",
        "favorable": {"humidity_min": 85, "temp_range": (20, 27), "rain_boost": True},
        "steps": ["Remove spotted lower leaves and destroy them",
                  "Spray chlorothalonil or mancozeb every 7-10 days",
                  "Mulch the soil and avoid splashing water on leaves"],
        "organic": "Neem oil spray (2%)",
        "dosage": "Chlorothalonil 75% WP — 2g/litre of water",
    },
    # Potato
    "potato_early_blight": {
        "label": "Potato — Early Blight", "crop": "Potato",
        "pathogen": "Alternaria solani (fungus)",
        "favorable": {"humidity_min": 80, "temp_range": (24, 29), "rain_boost": True},
        "steps": ["Remove and destroy affected lower leaves",
                  "Spray mancozeb every 7-10 days",
                  "Avoid water stress and give balanced fertilizer"],
        "organic": "Neem oil spray (2%)",
        "dosage": "Mancozeb 75% WP — 2.5g/litre of water",
    },
    # Rice
    "rice_bacterial_blight": {
        "label": "Rice — Bacterial Leaf Blight", "crop": "Rice",
        "pathogen": "Xanthomonas oryzae (bacterium)",
        "favorable": {"humidity_min": 80, "temp_range": (25, 34), "rain_boost": True},
        "steps": ["Drain the field and avoid excess nitrogen",
                  "Spray copper oxychloride with streptocycline",
                  "Do not move water or workers from infected to healthy plots"],
        "organic": "Fresh cow-dung extract (20%), clarified and sprayed",
        "dosage": "Copper oxychloride 2.5g + streptocycline 0.15g per litre of water",
    },
    "rice_brown_spot": {
        "label": "Rice — Brown Spot", "crop": "Rice",
        "pathogen": "Bipolaris oryzae (fungus)",
        "favorable": {"humidity_min": 80, "temp_range": (25, 30), "rain_boost": False},
        "steps": ["Spray mancozeb or propiconazole when spots appear",
                  "Correct nutrient deficiency — apply potash and balanced fertilizer",
                  "Use clean seed and treat seed before sowing next season"],
        "organic": "Pseudomonas fluorescens spray",
        "dosage": "Mancozeb 75% WP — 2.5g/litre of water",
    },
    "rice_sheath_blight": {
        "label": "Rice — Sheath Blight", "crop": "Rice",
        "pathogen": "Rhizoctonia solani (fungus)",
        "favorable": {"humidity_min": 85, "temp_range": (28, 32), "rain_boost": False},
        "steps": ["Spray hexaconazole or validamycin on the lower part of plants",
                  "Reduce nitrogen and avoid dense planting",
                  "Drain excess water and remove weeds on the bunds"],
        "organic": "Pseudomonas fluorescens spray",
        "dosage": "Hexaconazole 5% EC — 2ml/litre of water",
    },
    # Wheat
    "wheat_yellow_rust": {
        "label": "Wheat — Yellow Rust", "crop": "Wheat",
        "pathogen": "Puccinia striiformis (fungus)",
        "favorable": {"humidity_min": 70, "temp_range": (10, 18), "rain_boost": False},
        "steps": ["Spray propiconazole at the first yellow stripes",
                  "Inform neighbours — spores travel by wind",
                  "Grow rust-resistant varieties next season"],
        "organic": "Resistant varieties and early sulphur dust",
        "dosage": "Propiconazole 25% EC — 1ml/litre of water",
    },
    # Chilli
    "chilli_leaf_curl": {
        "label": "Chilli — Leaf Curl (thrips / mites / virus)", "crop": "Chilli",
        "pathogen": "Thrips and mite complex with leaf curl virus",
        "favorable": {"humidity_min": 40, "temp_range": (25, 35), "rain_boost": False},
        "steps": ["Remove and destroy severely curled plants",
                  "Spray fipronil or a mite-specific product against thrips and mites",
                  "Set blue and yellow sticky traps; keep field weed-free"],
        "organic": "Neem oil 5ml/litre plus blue sticky traps",
        "dosage": "Fipronil 5% SC — 1.5ml/litre of water",
    },
    "chilli_anthracnose": {
        "label": "Chilli — Anthracnose / Fruit Rot", "crop": "Chilli",
        "pathogen": "Colletotrichum capsici (fungus)",
        "favorable": {"humidity_min": 80, "temp_range": (26, 30), "rain_boost": True},
        "steps": ["Pick and destroy rotten fruits and dry twigs",
                  "Spray carbendazim or mancozeb at first sunken spots",
                  "Avoid overhead irrigation and use disease-free seed"],
        "organic": "Trichoderma viride spray",
        "dosage": "Carbendazim 50% WP — 1g/litre of water",
    },
    # Cotton
    "cotton_leaf_curl": {
        "label": "Cotton — Leaf Curl Virus", "crop": "Cotton",
        "pathogen": "Cotton leaf curl virus (spread by whitefly)",
        "favorable": {"humidity_min": 40, "temp_range": (25, 35), "rain_boost": False},
        "steps": ["Uproot infected young plants early and destroy them",
                  "Control whitefly with diafenthiuron as per label",
                  "Remove weeds like Abutilon and Parthenium near the field"],
        "organic": "Neem oil 5ml/litre plus yellow sticky traps",
        "dosage": "Diafenthiuron 50% WP — 1g/litre of water",
    },
    "cotton_bacterial_blight": {
        "label": "Cotton — Bacterial Blight", "crop": "Cotton",
        "pathogen": "Xanthomonas citri pv. malvacearum (bacterium)",
        "favorable": {"humidity_min": 75, "temp_range": (26, 35), "rain_boost": True},
        "steps": ["Spray copper oxychloride with streptocycline",
                  "Remove and burn crop residue after harvest",
                  "Use acid-delinted seed and avoid working in wet fields"],
        "organic": "Pseudomonas fluorescens spray",
        "dosage": "Copper oxychloride 3g + streptocycline 0.1g per litre of water",
    },
    "cotton_alternaria": {
        "label": "Cotton — Alternaria Leaf Spot", "crop": "Cotton",
        "pathogen": "Alternaria macrospora (fungus)",
        "favorable": {"humidity_min": 80, "temp_range": (25, 30), "rain_boost": True},
        "steps": ["Spray mancozeb or propiconazole at first spots",
                  "Apply potash — deficiency makes the disease worse",
                  "Remove fallen infected leaves"],
        "organic": "Neem oil spray (2%)",
        "dosage": "Mancozeb 75% WP — 2.5g/litre of water",
    },
    # Groundnut
    "groundnut_tikka": {
        "label": "Groundnut — Tikka (Leaf Spot)", "crop": "Groundnut",
        "pathogen": "Cercospora arachidicola / Phaeoisariopsis personata (fungus)",
        "favorable": {"humidity_min": 80, "temp_range": (25, 30), "rain_boost": True},
        "steps": ["Spray chlorothalonil at the first dark leaf spots",
                  "Repeat after 12-15 days if humid weather continues",
                  "Rotate crops and destroy crop residue after harvest"],
        "organic": "Neem seed kernel extract (5%)",
        "dosage": "Chlorothalonil 75% WP — 2g/litre of water",
    },
    "groundnut_rust": {
        "label": "Groundnut — Rust", "crop": "Groundnut",
        "pathogen": "Puccinia arachidis (fungus)",
        "favorable": {"humidity_min": 80, "temp_range": (20, 26), "rain_boost": True},
        "steps": ["Spray chlorothalonil or tebuconazole when orange pustules appear",
                  "Avoid late sowing and dense crop stands",
                  "Remove volunteer groundnut plants from the field edge"],
        "organic": "Neem seed kernel extract (5%)",
        "dosage": "Chlorothalonil 75% WP — 2g/litre of water",
    },
    # Maize
    "maize_northern_leaf_blight": {
        "label": "Maize — Northern Leaf Blight", "crop": "Maize",
        "pathogen": "Exserohilum turcicum (fungus)",
        "favorable": {"humidity_min": 80, "temp_range": (18, 27), "rain_boost": True},
        "steps": ["Spray mancozeb or propiconazole when long grey lesions appear",
                  "Rotate with non-cereal crops and bury residue after harvest",
                  "Grow tolerant hybrids next season"],
        "organic": "Neem oil spray (2%)",
        "dosage": "Mancozeb 75% WP — 2.5g/litre of water",
    },
    "maize_common_rust": {
        "label": "Maize — Common Rust", "crop": "Maize",
        "pathogen": "Puccinia sorghi (fungus)",
        "favorable": {"humidity_min": 75, "temp_range": (16, 25), "rain_boost": False},
        "steps": ["Spray propiconazole when brown pustules appear on both leaf sides",
                  "Avoid excess nitrogen",
                  "Check nearby fields — spores spread by wind"],
        "organic": "Sulphur dust in early stage",
        "dosage": "Propiconazole 25% EC — 1ml/litre of water",
    },
    "maize_fall_armyworm": {
        "label": "Maize — Fall Armyworm", "crop": "Maize",
        "pathogen": None,
        "favorable": {"humidity_min": 50, "temp_range": (25, 32), "rain_boost": False},
        "steps": ["Look inside the whorl for caterpillars and frass (sawdust-like droppings)",
                  "Spray emamectin benzoate into the whorl, early morning or evening",
                  "Set pheromone traps (about 5 per acre) to track moths"],
        "organic": "Neem seed kernel extract (5%) or Bt spray",
        "dosage": "Emamectin benzoate 5% SG — 0.4g/litre of water",
    },
    # Banana
    "banana_sigatoka": {
        "label": "Banana — Sigatoka Leaf Spot", "crop": "Banana",
        "pathogen": "Mycosphaerella spp. (fungus)",
        "favorable": {"humidity_min": 80, "temp_range": (25, 28), "rain_boost": True},
        "steps": ["Cut and destroy heavily spotted leaves",
                  "Spray propiconazole or carbendazim",
                  "Improve drainage and avoid overcrowding of suckers"],
        "organic": "Neem oil 3% with a sticker",
        "dosage": "Propiconazole 25% EC — 1ml/litre of water",
    },
    # Sugarcane
    "sugarcane_red_rot": {
        "label": "Sugarcane — Red Rot", "crop": "Sugarcane",
        "pathogen": "Colletotrichum falcatum (fungus)",
        "favorable": {"humidity_min": 80, "temp_range": (28, 32), "rain_boost": True},
        "steps": ["Uproot and burn affected clumps; do not ratoon this field",
                  "Drench the pit with carbendazim to stop spread to neighbouring clumps",
                  "Next season use healthy, resistant setts and treat them before planting"],
        "organic": "Trichoderma viride mixed into the soil",
        "dosage": "Carbendazim 50% WP — 1g/litre of water (drench / sett dip)",
    },
    "sugarcane_rust": {
        "label": "Sugarcane — Rust", "crop": "Sugarcane",
        "pathogen": "Puccinia melanocephala (fungus)",
        "favorable": {"humidity_min": 80, "temp_range": (22, 28), "rain_boost": False},
        "steps": ["Spray propiconazole at the first orange-brown pustules",
                  "Remove dry leaves and avoid excess nitrogen",
                  "Plant tolerant varieties next season"],
        "organic": "Sulfur dust application in early stages",
        "dosage": "Propiconazole 25% EC — 1ml/litre of water",
    },
    "sugarcane_yellow_leaf": {
        "label": "Sugarcane — Yellow Leaf Disease", "crop": "Sugarcane",
        "pathogen": "Sugarcane yellow leaf virus (spread by aphids)",
        "favorable": {"humidity_min": 40, "temp_range": (25, 35), "rain_boost": False},
        "steps": ["Uproot and destroy badly affected clumps — a virus cannot be cured",
                  "Control the aphid carriers with imidacloprid as per label",
                  "Plant only virus-free (tissue-culture) setts next season"],
        "organic": "Neem oil 5ml/litre plus virus-free tissue-culture seed",
        "dosage": "Imidacloprid 17.8% SL — 0.3ml/litre of water",
    },
    "sugarcane_woolly_aphid": {
        "label": "Sugarcane — Woolly Aphid", "crop": "Sugarcane", "pathogen": None,
        "favorable": {"humidity_min": 60, "temp_range": (26, 32), "rain_boost": False},
        "steps": ["Check leaf undersides for white cottony colonies",
                  "Spray dimethoate only if the attack is severe",
                  "Protect natural enemies (Dipha, Micromus) — avoid unnecessary spraying"],
        "organic": "Neem oil 5ml/litre; conserve or release Dipha aphidivora predators",
        "dosage": "Dimethoate 30% EC — 2ml/litre of water",
    },
    # Tomato (bacterial)
    "tomato_bacterial_spot": {
        "label": "Tomato — Bacterial Spot", "crop": "Tomato",
        "pathogen": "Xanthomonas spp. (bacterium)",
        "favorable": {"humidity_min": 80, "temp_range": (24, 30), "rain_boost": True},
        "steps": ["Spray copper oxychloride with streptocycline at first spots",
                  "Avoid overhead irrigation and do not work in the field when plants are wet",
                  "Remove badly infected leaves and burn crop residue after harvest"],
        "organic": "Pseudomonas fluorescens spray",
        "dosage": "Copper oxychloride 3g + streptocycline 0.1g per litre of water",
    },
    # Mango
    "mango_powdery_mildew": {
        "label": "Mango — Powdery Mildew", "crop": "Mango",
        "pathogen": "Oidium mangiferae (fungus)",
        "favorable": {"humidity_min": 70, "temp_range": (18, 28), "rain_boost": False},
        "steps": ["Spray wettable sulphur when white powder appears on flower panicles",
                  "Repeat after about 15 days if humid or cloudy weather continues",
                  "Prune dense branches for airflow; avoid spraying sulphur in the heat of midday"],
        "organic": "Diluted buttermilk spray",
        "dosage": "Wettable sulphur 80% WP — 2g/litre of water",
    },
    "mango_anthracnose": {
        "label": "Mango — Anthracnose", "crop": "Mango",
        "pathogen": "Colletotrichum gloeosporioides (fungus)",
        "favorable": {"humidity_min": 85, "temp_range": (25, 30), "rain_boost": True},
        "steps": ["Prune and burn dry twigs and infected leaves",
                  "Spray carbendazim at flowering and fruit set",
                  "Repeat if wet weather continues; avoid injuring fruits at harvest"],
        "organic": "Bordeaux mixture 1%",
        "dosage": "Carbendazim 50% WP — 1g/litre of water",
    },
    # Onion
    "onion_purple_blotch": {
        "label": "Onion — Purple Blotch", "crop": "Onion",
        "pathogen": "Alternaria porri (fungus)",
        "favorable": {"humidity_min": 80, "temp_range": (20, 30), "rain_boost": True},
        "steps": ["Spray mancozeb with a sticker at the first purple-white spots",
                  "Avoid overhead watering and dense planting",
                  "Rotate with non-onion crops for at least 2 seasons"],
        "organic": "Neem oil spray (2%)",
        "dosage": "Mancozeb 75% WP — 2.5g/litre of water (add a sticker)",
    },
    # General pest
    "pest_mite": {
        "label": "Pest — Spider Mites", "crop": "Any", "pathogen": None,
        "favorable": {"humidity_min": 30, "temp_range": (28, 38), "rain_boost": False},
        "steps": ["Check the underside of leaves for tiny mites and fine webbing",
                  "Spray abamectin or wettable sulphur as per label",
                  "Avoid dusty conditions and water stress"],
        "organic": "Neem oil spray or a strong water jet on leaf undersides",
        "dosage": "Abamectin 1.8% EC — 0.5ml/litre of water",
    },
}

# Which diseases the classifier may choose from for each crop the farmer picks.
CROP_DISEASES = {
    "tomato": ["tomato_early_blight", "tomato_late_blight", "tomato_septoria", "tomato_bacterial_spot", "tomato_leaf_curl",
               "pest_aphid", "pest_mite", "healthy"],
    "potato": ["potato_late_blight", "potato_early_blight", "pest_aphid", "healthy"],
    "wheat": ["wheat_leaf_rust", "wheat_yellow_rust", "wheat_powdery_mildew", "pest_aphid", "healthy"],
    "rice": ["rice_blast", "rice_bacterial_blight", "rice_brown_spot", "rice_sheath_blight", "healthy"],
    "chilli": ["chilli_leaf_curl", "chilli_anthracnose", "pest_aphid", "pest_mite", "healthy"],
    "cotton": ["cotton_leaf_curl", "cotton_bacterial_blight", "cotton_alternaria", "pest_aphid",
               "pest_mite", "healthy"],
    "groundnut": ["groundnut_tikka", "groundnut_rust", "pest_aphid", "healthy"],
    "maize": ["maize_northern_leaf_blight", "maize_common_rust", "maize_fall_armyworm", "healthy"],
    "banana": ["banana_sigatoka", "pest_aphid", "healthy"],
    "mango": ["mango_powdery_mildew", "mango_anthracnose", "healthy"],
    "onion": ["onion_purple_blotch", "healthy"],
    "sugarcane": ["sugarcane_red_rot", "sugarcane_rust", "sugarcane_yellow_leaf", "sugarcane_woolly_aphid", "healthy"],
}

# Derived views used by app.py
DISEASE_LIBRARY = {k: {f: v[f] for f in ("label", "crop", "pathogen", "favorable")} for k, v in DISEASES.items()}
RECOMMENDATIONS = {k: {"steps": v["steps"], "organic_alternative": v["organic"], "dosage": v["dosage"]}
                   for k, v in DISEASES.items()}
ALL_IDS = list(DISEASES)
